# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=56)),
                ('respondent', models.CharField(max_length=256)),
                ('respondent_position', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('resolution', models.TextField()),
                ('complaint_date', models.DateField(null=True)),
                ('staff_or_student', models.CharField(max_length=12)),
                ('is_still_employed', models.NullBooleanField()),
                ('identifier', models.CharField(max_length=256, unique=True)),
                ('documentcloud_id', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['-complaint_date'],
            },
        ),
    ]
