# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='documentcloud_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
