# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-09 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0003_case_clarification'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='correction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='clarification',
            field=models.TextField(null=True),
        ),
    ]
