# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0003_case_complaint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='staff_or_student',
            field=models.CharField(default='t', max_length=12),
            preserve_default=False,
        ),
    ]
