# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0004_case_staff_or_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='respondant',
            new_name='respondent',
        ),
    ]
