# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0004_auto_20170409_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='include',
            field=models.NullBooleanField(),
        ),
    ]
