# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0006_auto_20160924_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='resolution',
            field=models.TextField(default='2'),
            preserve_default=False,
        ),
    ]
