# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0007_case_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='campus',
            field=models.CharField(default='B', max_length=56),
            preserve_default=False,
        ),
    ]
