# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 07:30
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0008_case_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='hi', editable=False, populate_from=b'respondent'),
            preserve_default=False,
        ),
    ]
