# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0009_case_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='report',
            field=models.FileField(default='null', upload_to=b''),
            preserve_default=False,
        ),
    ]
