# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import misconduct.models


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0010_case_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_still_employed',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='report',
            field=models.FileField(upload_to=misconduct.models.report_file_name),
        ),
    ]
