# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-01 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0011_auto_20160924_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-complaint_date']},
        ),
        migrations.AddField(
            model_name='case',
            name='identifier',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(),
        ),
    ]
