# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0012_auto_20170301_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='documentcloud_identifier',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
