# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misconduct', '0013_case_documentcloud_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='documentcloud_identifier',
            new_name='documentcloud_id',
        ),
    ]
